name: run-job
description:

inputs:
  action:
    description:
    required: true
  target:
    description:
    required: false
  version:
    description:
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: dylni/build-actions
    - run: mv '${{ inputs.action }}' ../action
      shell: bash
    - uses: ./../action
      with:
        target: ${{ inputs.target }}
        version: ${{ inputs.version }}
    - run: |
        perl -pi -e 's/(unix_waitid=)not\b/\1all/' src/cfg-aliases.txt
        perl -pi -e 's/(unix), any\(.*?\)/\1/' Cargo.toml
        perl -0pi -e 's/(\n *- )uses: dylni\/build-actions\/setup@.*?\1/\1/s' ../action/action.yml
      shell: bash
    - uses: ./../action
      with:
        target: ${{ inputs.target }}
        version: ${{ inputs.version }}
