name: build

on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * FRI

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: dylni/process_control/.github/actions/run-job@master
      with:
        action: build
    timeout-minutes: 20
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
  build-other:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: dylni/process_control/.github/actions/run-job@master
      with:
        action: build-other
        target: ${{ matrix.target }}
        version: ${{ matrix.version }}
    timeout-minutes: 20
    strategy:
      matrix:
        target: [x86_64-unknown-freebsd, x86_64-unknown-illumos]
        version: [1.74.0, stable, beta, nightly]
  test:
    needs: [build]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: dylni/process_control/.github/actions/run-job@master
      with:
        action: test
        version: ${{ matrix.version }}
    timeout-minutes: 20
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        version: [1.74.0, stable, beta, nightly]
